image: python:latest

cache:
  paths:
    - ~/.cache/pip/

stages:
  - lint
  - unittest
  - deploy-docs

before_script:
  - python -V  # Print out python version for debugging

test-flake8:
  stage: lint
  script:
    - pip install flake8
    - flake8 knoxth

test-black:
  stage: lint
  script:
    - pip install black
    - black --check --diff knoxth setup.py

test-tox:
  stage: unittest
  image: themattrix/tox
  script:
    - pip install tox
    - tox
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy-docs
  script:
  - pip install mkdocs
  - mkdocs build --strict --verbose -d public
  - mv coverage public/
  artifacts:
    paths:
    - public
  only:
  - master
