image: python:latest

cache:
  paths:
    - ~/.cache/pip/

stages:
  - lint
  - unittest

before_script:
  - python -V  # Print out python version for debugging
  - pip install pipenv
  - pipenv install --dev

test-flake8:
  stage: lint
  script:
    - pipenv run flake8 knoxth

test-isort:
  stage: lint
  script:
    - pipenv run isort --check-only --diff knoxth setup.py

test-tox:
  stage: unittest
  image: themattrix/tox
  script:
    - cd tests/tests
    - pipenv run tox
