# Generated by Django 2.2.22 on 2021-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knoxth", "0002_claim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="context",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
