# Generated by Django 3.2.2 on 2021-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knoxth", "0005_auto_20210515_0950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="context",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
