# Generated by Django 3.2.3 on 2021-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knoxth", "0006_auto_20210515_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="name",
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
