#+TITLE: KNOXTH AUTHENTICATION AND AUTHORIZATION FLOW
#+AUTHOR: Ayush Jha
#+SETUPFILE: testapi.theme

* knoxth authentication & authorization flow                           :verb:
# Manually testing knoxth API
template http://localhost:8000/
Accept: application/json

** Get authorization token
:properties:
:Verb-Store: auth-code
:end:
# Get the authorization token from /authorize endpoint by passing it
# username and password

post /api/authorize/
Content-Type: application/json; charset=utf-8

{
    "username": "{{(read-string "Username: " "admin")}}",
    "password": "{{(read-string "Password: " "a")}}"
}

** Get Access token by passing in the authorization token
   :properties:
   :Verb-Store: access-token
   :end:
# Use Emacs Lisp code tags to make the request
# content dynamic. Code tags can be used anywhere
# in the request specification.

post /api/login/
Authorization: Token {{(read-string "Authorization Code:" (verb-json-get (oref (verb-stored-response "auth-code") body) "token"))}}

** Logout of all places

   :properties:
   :Verb-Store: access-token
   :end:
# Use Emacs Lisp code tags to make the request
# content dynamic. Code tags can be used anywhere
# in the request specification.

post /api/logoutall/
Authorization: Token {{(read-string "Access Token: " (verb-json-get (oref (verb-stored-response "access-token") body) "token"))}}

** Logout of current session (invalidate token)

   :properties:
   :Verb-Store: access-token
   :end:
# Use Emacs Lisp code tags to make the request
# content dynamic. Code tags can be used anywhere
# in the request specification.

post /api/logout/
Authorization: Token {{(read-string "Access Token: " (verb-json-get (oref (verb-stored-response "access-token") body) "token"))}}

** List all possible contexts
# Return json list of all contexts available to user
get /api/contexts/
Authorization: Token {{(read-string "Access Token: " (verb-json-get (oref (verb-stored-response "access-token") body) "token"))}}

** List all tokens for user
# List of all the tokens created for this user
get /api/tokens/
Authorization: Token {{(read-string "Access Token: " (verb-json-get (oref (verb-stored-response "access-token") body) "token"))}}

** Create a new token with specified contexts and scopes
# List of all the tokens created for this user
post /api/tokens/
Authorization: Token {{(read-string "Access Token: " (verb-json-get (oref (verb-stored-response "access-token") body) "token"))}}
Content-Type: application/json

{"scopes": [{
"context": "home",
"permissions_set": ["access", "modify"]
},
{
"context": "home",
"permissions_set": ["delete"]
}]}

** Home View Test
# List of all the tokens created for this user
get /users/
Authorization: Token 4efd1c6a6e005126de8dde71eaba979eacef52be1a5f938523e846d325c9eb21
